---
name: Static analysis and unit tests
run-name: Running static analysis and unit tests
on:
  push:
    branches: master
    paths-ignore: 
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository on to Github Actions runner
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'

      - name: Install hatch, a python build and environment manager
        run: pip install hatch

      # For the script definitions, please see `pyproject.toml`
      - name: Run type checking with mypy
        continue-on-error: true
        run: hatch run type-check

      - name: Run static analysis with ruff
        continue-on-error: true
        run: hatch run ruff-check

      - name: Run unit tests with unittest
        continue-on-error: true
        run: hatch run unit-tests
 