---
name: Static analysis and unit tests
run-name: Running static analysis and unit tests
on:
  push:
    branches: master
    paths-ignore: 
      - '**.md'
      - '.gitignore'
      - '.gitattributes'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository on to Github Actions runner
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'

      - name: Install dependencies with pip from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run static analysis with mypy
        continue-on-error: true
        run: mypy pytorch_influence_functions

      - name: Run unit tests with unittest
        continue-on-error: true
        run: python -m unittest -v
 